lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%' # required for token creation
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%' # required for token verification
    token_ttl: 3600
    pass_phrase: '%env(JWT_PASSPHRASE)%'
